### ISSUE TITLE
cant show cpu temperature on Orangepi 5（with rk3588s）

### ISSUE THREAD

**Issue by talking-toaster** [htop-dev/htop#1160]
I use Ubuntu jummy and install the htop (3.0.5-7build2)
![image](https://user-images.githubusercontent.com/49156890/210499616-027e863c-80e5-4a27-bb84-1626205d4f83.png)

this is `sensor -u`

```
orangepi@orangepi5:~/code$ sensors -u
gpu_thermal-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 33.307

littlecore_thermal-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 34.230

bigcore0_thermal-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 34.230

tcpm_source_psy_6_0022-i2c-6-22
Adapter: rk3x-i2c
in0:
  in0_input: 0.000
  in0_min: 0.000
  in0_max: 0.000
curr1:
  curr1_input: 0.000
  curr1_max: 0.000

npu_thermal-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 34.230

center_thermal-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 34.230

bigcore1_thermal-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 34.230

soc_thermal-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 34.230
  temp1_crit: 115.000

```
