### ISSUE TITLE
Migrate away from deprecated ncurses functions `attrset`, `attron` and `attroff`

### ISSUE THREAD

**Issue by C0rn3j** [htop-dev/htop#1541]
https://invisible-island.net/ncurses/man/curs_attr.3x.html

Perhaps even just use wide characters by default with `wattr_on`/`wattr_off`/`wattr_set`?  
In which case other things also have to be migrated, see https://invisible-island.net/ncurses/man/curs_attr.3x.html#h2-PORTABILITY

Ran into this while trying to fix https://github.com/htop-dev/htop/issues/243

attron -> attr_on
```yaml
% grep -R attron 2>/dev/null
CRT.c:   attron(resetColor);
```

attroff -> attr_off
```yaml
% grep -R attroff 2>/dev/null
CRT.c:   attroff(resetColor);
```

attrset -> attr_set
```yaml
% grep -R attrset 2>/dev/null
Action.c:   attrset(attr);
Action.c:   attrset(CRT_colors[HELP_BOLD]);
Action.c:   attrset(CRT_colors[DEFAULT_COLOR]);
Action.c:   attrset(CRT_colors[DEFAULT_COLOR]);
Action.c:   attrset(CRT_colors[DEFAULT_COLOR]);
Action.c:   attrset(CRT_colors[DEFAULT_COLOR]);
Action.c:   attrset(CRT_colors[DEFAULT_COLOR]);
Action.c:      attrset((helpLeft[item].roInactive && readonly) ? CRT_colors[HELP_SHADOW] : CRT_colors[DEFAULT_COLOR]);
Action.c:      attrset((helpLeft[item].roInactive && readonly) ? CRT_colors[HELP_SHADOW] : CRT_colors[HELP_BOLD]);
Action.c:         attrset((helpLeft[item].roInactive && readonly) ? CRT_colors[HELP_SHADOW] : CRT_colors[PROCESS_THREAD]);
Action.c:         attrset((helpLeft[item].roInactive && readonly) ? CRT_colors[HELP_SHADOW] : CRT_colors[PROCESS_THREAD]);
Action.c:      attrset((helpRight[item].roInactive && readonly) ? CRT_colors[HELP_SHADOW] : CRT_colors[HELP_BOLD]);
Action.c:      attrset((helpRight[item].roInactive && readonly) ? CRT_colors[HELP_SHADOW] : CRT_colors[DEFAULT_COLOR]);
Action.c:   attrset(CRT_colors[HELP_BOLD]);
Action.c:   attrset(CRT_colors[DEFAULT_COLOR]);
Meter.c:   attrset(CRT_colors[METER_TEXT]);
Meter.c:   attrset(CRT_colors[RESET_COLOR]);
Meter.c:   attrset(CRT_colors[METER_TEXT]);
Meter.c:   attrset(CRT_colors[BAR_BORDER]);
Meter.c:   attrset(CRT_colors[RESET_COLOR]);
Meter.c:   attrset(CRT_colors[RESET_COLOR]);
Meter.c:   attrset(CRT_colors[METER_TEXT]);
Meter.c:         attrset(CRT_colors[colorIdx]);
Meter.c:   attrset(CRT_colors[RESET_COLOR]);
Meter.c:   attrset(CRT_colors[LED_COLOR]);
Meter.c:         const cchar_t wc = { .chars = { c, '\0' }, .attr = 0 }; /* use LED_COLOR from attrset() */
Meter.c:   attrset(CRT_colors[RESET_COLOR]);
InfoScreen.c:   attrset(CRT_colors[METER_TEXT]);
InfoScreen.c:   attrset(CRT_colors[DEFAULT_COLOR]);
ScreenManager.c:   attrset(CRT_colors[cur ? SCREENS_CUR_BORDER : SCREENS_OTH_BORDER]);
ScreenManager.c:   attrset(CRT_colors[cur ? SCREENS_CUR_TEXT : SCREENS_OTH_TEXT]);
ScreenManager.c:   attrset(CRT_colors[cur ? SCREENS_CUR_BORDER : SCREENS_OTH_BORDER]);
ScreenManager.c:   attrset(CRT_colors[RESET_COLOR]);
FunctionBar.c:   attrset(CRT_colors[FUNCTION_BAR]);
FunctionBar.c:      attrset(CRT_colors[FUNCTION_KEY]);
FunctionBar.c:      attrset(CRT_colors[FUNCTION_BAR]);
FunctionBar.c:         attrset(CRT_colors[FUNCTION_BAR]);
FunctionBar.c:         attrset(attr);
FunctionBar.c:   attrset(CRT_colors[RESET_COLOR]);
FunctionBar.c:      attrset(CRT_colors[FUNCTION_BAR]);
FunctionBar.c:      attrset(attr);
FunctionBar.c:   attrset(CRT_colors[RESET_COLOR]);
Header.c:   attrset(CRT_colors[RESET_COLOR]);
Panel.c:      attrset(header_attr);
Panel.c:      attrset(CRT_colors[RESET_COLOR]);
Panel.c:            attrset(item.highlightAttr);
Panel.c:            attrset(CRT_colors[RESET_COLOR]);
Panel.c:      attrset(selectionColor);
Panel.c:      attrset(CRT_colors[RESET_COLOR]);
```

*Any arguments about old distributions can rest, as those distributions will simply use old htop, even Ubuntu 20.04 from 2020 has ncurses 6.2... and htop 2.2.0.*
