### ISSUE TITLE
Crash after shutting down Docker container

### ISSUE THREAD

**Issue by Spanfile** [htop-dev/htop#270]
```
$ htop --version
htop 3.0.3-dev
$ uname -a
Linux workstation 5.9.1-xanmod1 #0~git20201018.7d8871a SMP PREEMPT Sun Oct 18 12:59:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```
```
Error information:
------------------
A signal 6 (Aborted) was received.

Backtrace information:
----------------------
The following function calls were active when the issue was detected:
---
htop(CRT_handleSIGSEGV+0xa7)[0x55c8a98140e7]
/lib/x86_64-linux-gnu/libc.so.6(+0x41950)[0x7fc070b5f950]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fc070b5f8cb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x116)[0x7fc070b44864]
htop(+0x1fab4)[0x55c8a9820ab4]
htop(xSnprintf+0xce)[0x55c8a98210fe]
htop(+0x187b9)[0x55c8a98197b9]
htop(+0x17ad2)[0x55c8a9818ad2]
htop(Header_draw+0x102)[0x55c8a98160e2]
htop(ScreenManager_run+0x18e)[0x55c8a981d9ee]
htop(main+0x513)[0x55c8a980f723]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2)[0x7fc070b46cb2]
htop(_start+0x2e)[0x55c8a980f91e]
```

Steps to reproduce:
* Start a Docker container with `docker-compose up -d`. I've used the following `docker-compose.yml`:

```
---
version: '3.8'
services:
  psql:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - '127.0.0.1:5432:5432'
```
* Run `htop` in a separate shell
* Shut down the container with `docker-compose down`

I've built `htop` manually from the latest commit. I've configured it to display the network and disk IO meters, maybe they have something to do with the crash?

[htop.objdump.tar.gz](https://github.com/htop-dev/htop/files/5409985/htop.objdump.tar.gz)
