### ISSUE TITLE
Missing temperature for some threads

### ISSUE THREAD

**Issue by somera** [htop-dev/htop#856]
I'm using self compiled 3.1.1 release.

On one computer I missing temperature for threads 5-8

![image](https://user-images.githubusercontent.com/8334250/138566449-a6f83953-379e-4780-a66b-9a2939cf92e3.png)

In btop++ I see temperature for all cores

![image](https://user-images.githubusercontent.com/8334250/138566496-890dd5eb-34c4-4791-89cc-f0813fb65256.png)

For the same CPU on other computer it's all fine

![image](https://user-images.githubusercontent.com/8334250/138566466-6cd95ef4-a005-44d5-b156-de984e0faaa5.png)

**Comment by somera** [comment]
> At this very moment in time.
> 
> ```
> htop> ./htop --version
> htop 3.2.0-dev
> htop> sensors --version
> sensors version 3.5.0 with libsensors version 3.5.0
> ```
> 
> ```
> htop> sensors -u
> coretemp-isa-0000
> Adapter: ISA adapter
> Package id 0:
>   temp1_input: 48.000
>   temp1_max: 80.000
>   temp1_crit: 98.000
>   temp1_crit_alarm: 0.000
> Core 0:
>   temp2_input: 25.000
>   temp2_max: 80.000
>   temp2_crit: 98.000
>   temp2_crit_alarm: 0.000
> Core 1:
>   temp3_input: 36.000
>   temp3_max: 80.000
>   temp3_crit: 98.000
>   temp3_crit_alarm: 0.000
> Core 2:
>   temp4_input: 48.000
>   temp4_max: 80.000
>   temp4_crit: 98.000
>   temp4_crit_alarm: 0.000
> Core 3:
>   temp5_input: 37.000
>   temp5_max: 80.000
>   temp5_crit: 98.000
>   temp5_crit_alarm: 0.000
> ```
> 
> `./htop` ![htop-i7](https://user-images.githubusercontent.com/48602507/139472904-17e34830-7793-4c57-a084-9973c7f3350f.png)

Fot me not ...

```
$ sensors --version
sensors version 3.6.0 with libsensors version 3.6.0
$ ./htop --version
htop 3.2.0-dev
$ git log -1 --format="%H"
63fafb4844dd619793ba1d318e2b06518666dd37
```

![image](https://user-images.githubusercontent.com/8334250/145262680-50dcf6f9-9a32-4889-b192-d5f90f79e1dd.png)

**Comment by The-going** [comment]
> sensors --version
> sensors version 3.6.0 with libsensors version 3.6.0

Thanks for the information. Your picture shows the truth. I should change 'sensors` to a more up-to-date version.

**Comment by somera** [comment]
> sensors version 3.5.0 with libsensors version 3.5.0

That means, that with

`sensors version 3.5.0 with libsensors version 3.5.0`

and with

`sensors version 3.6.0 with libsensors version 3.6.0`

not?

I didn't check this with 3.5.0.

**Comment by The-going** [comment]
There are 4 physical cores in this processor. There is a temperature sensor on each physical core. Another sensor shows the temperature of the GPU. There are 5 of them in total. In your picture, numbers 5, 6, 7, 8 are virtual cores. They don't have sensors. Your picture shows the truth, and my green one is a lie.

**Comment by Zorrototo** [comment]
Here with a Ryzen 5 3600 I have temperature missing in `htop` on all but one core.

```
sensors -u
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:
  temp1_input: 65.750
Tccd1:
  temp3_input: 65.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 16.800
  temp1_crit: 20.800
temp2:
  temp2_input: 16.800
  temp2_crit: 20.800

nvme-pci-0100
Adapter: PCI adapter
Composite:
  temp1_input: 46.850
  temp1_max: 86.850
  temp1_min: -0.150
  temp1_crit: 89.850
  temp1_alarm: 0.000
Sensor 1:
  temp2_input: 46.850
  temp2_max: 65261.850
  temp2_min: -273.150

```

https://i.imgur.com/ZNFWApZ.jpg
